import type { Metadata } from "next";
import { Provider as TooltipProvider } from "@radix-ui/react-tooltip";
import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "@/lib/cart-context"; // 👈 нэмнэ

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* CartProvider-оор бүх children-ээ орооно */}
        <CartProvider>
          {/* TooltipProvider-г мөн хадгална */}
          <TooltipProvider>{children}</TooltipProvider>
        </CartProvider>
      </body>
    </html>
  );
}
